[package]
name = "libregpt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
hyper = { version = "0.14", features = ["client", "http1", "http2", "runtime", "server"] }
hyper-rustls = { version = "0.24", features = ["http2"] }
rand_user_agent = "0.0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"]}
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2"
