[package]
name = "gpt"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "0.14", features = ["http1", "http2", "runtime", "server"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"]}
tracing = "0.1"
tracing-subscriber = "0.3"
